# Generated by Django 4.2.3 on 2024-01-07 01:24

import random
import string

from django.contrib.auth import get_user_model
from django.contrib.auth.hashers import make_password
from django.db import migrations


def generate_random_string(length=20):
    # Define the character set from which to generate the string
    characters = (
        string.ascii_letters + string.digits
    )  # You can add more characters if needed

    # Use random.choices to generate the random string
    random_string = "".join(random.choices(characters, k=length))

    return random_string


def create_raijin_bot(apps, schema_editor):
    User = apps.get_model("api", "User")
    bot = User(
        email="bot@raijin.ai",
        username="bot@raijin.ai",
        first_name="Created by AI",
        last_name="",
        password=make_password(generate_random_string()),
    )
    bot.save()


def revert_create_raijin_bot(apps, schema_editor):
    User = get_user_model()
    User.objects.get(username="bot@raijin.ai").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(
            code=create_raijin_bot,
            reverse_code=revert_create_raijin_bot,
        ),
    ]
