# Generated by Django 4.2.3 on 2024-01-15 06:17

import django.db.models.deletion
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import migrations, models


def set_workspace_owned_by_to_first_joined_member(apps, schema_editor):
    User = get_user_model()
    Workspace = apps.get_model("api", "Workspace")
    workspaces_to_update = []
    for workspace in Workspace.objects.all():
        if workspace.owned_by is not None:
            continue

        if workspace.members.count() == 0:
            if User.objects.filter(projects__workspace=workspace.id).count() == 0:
                # Clean up workspaces with no users
                workspace.delete()
                continue

            # If workspace doesn't have members, but workspace.project has
            workspace.owned_by = User.objects.filter(
                projects__workspace=workspace.id
            ).earliest("date_joined")
        else:
            # Workspace has members
            workspace.owned_by = workspace.members.earliest("date_joined")
        workspaces_to_update.append(workspace)
    Workspace.objects.bulk_update(workspaces_to_update, ["owned_by"])


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_workspace_owned_by"),
    ]

    operations = [
        migrations.RunPython(
            code=set_workspace_owned_by_to_first_joined_member,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="workspace",
            name="owned_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="owned_workspaces",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
