# Generated by Django 4.2.3 on 2024-01-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_project_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takeaway',
            name='status',
        ),
        migrations.AddField(
            model_name='takeaway',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Med', 'Med'), ('High', 'High')], max_length=4, null=True),
        ),
    ]
