# Generated by Django 4.2.3 on 2024-01-24 08:40

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_note_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='takeaway_count',
        ),
        migrations.AddField(
            model_name='takeaway',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='notes', to='api.keyword'),
        ),
        migrations.CreateModel(
            name='TakeawayType',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=12, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takeaway_types', to='api.project')),
            ],
            options={
                'unique_together': {('project', 'name')},
            },
        ),
        migrations.AddField(
            model_name='takeaway',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='takeaways', to='api.takeawaytype'),
        ),
    ]
