# Generated by Django 4.2.3 on 2024-01-31 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_workspace_owned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takeaway',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='takeaways', to='api.takeawaytype'),
        ),
    ]
