# Generated by Django 4.2.3 on 2024-02-03 09:35

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_takeaway_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteTemplate',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=12, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='note_templates', to='api.project')),
            ],
        ),
        migrations.AlterField(
            model_name='note',
            name='keywords',
            field=models.ManyToManyField(related_name='notes', to='api.keyword'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=12, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.project')),
            ],
            options={
                'unique_together': {('project', 'title')},
            },
        ),
        migrations.CreateModel(
            name='NoteTemplateQuestion',
            fields=[
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=12, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('note_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.notetemplate')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question')),
            ],
            options={
                'ordering': ('note_template', 'order'),
                'unique_together': {('note_template', 'question')},
            },
        ),
        migrations.AddField(
            model_name='notetemplate',
            name='questions',
            field=models.ManyToManyField(related_name='note_templates', through='api.NoteTemplateQuestion', to='api.question'),
        ),
        migrations.CreateModel(
            name='NoteQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.note')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question')),
            ],
            options={
                'ordering': ('note', 'order'),
                'unique_together': {('note', 'question')},
            },
        ),
        migrations.AddField(
            model_name='note',
            name='questions',
            field=models.ManyToManyField(related_name='notes', through='api.NoteQuestion', to='api.question'),
        ),
        migrations.AddField(
            model_name='takeaway',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='takeaways', to='api.question'),
        ),
    ]
