# Generated by Django 4.2.3 on 2024-02-07 14:44

from django.db import migrations, models


def set_file_size(apps, schema_editor):
    Note = apps.get_model("api", "Note")
    notes = Note.objects.exclude(file="")
    for note in notes:
        try:
            note.file_size = note.file.size
        except FileNotFoundError:
            pass
    Note.objects.bulk_update(notes, ["file_size"])


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_notetemplate_alter_note_keywords_question_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="file_size",
            field=models.IntegerField(
                help_text="File size measured in bytes.", null=True
            ),
        ),
        migrations.RunPython(
            code=set_file_size,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name="note",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
