# Generated by Django 4.2.3 on 2024-02-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_user_skip_tutorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='key_themes',
            field=models.JSONField(default=list),
        ),
    ]
