# Generated by Django 4.2.3 on 2024-02-27 08:37

import api.models.user
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_project_key_themes'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', api.models.user.CustomUserManager()),
            ],
        ),
    ]
