# Generated by Django 4.2.3 on 2024-03-01 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0019_user_consent_given'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='analyzing_cost',
        ),
        migrations.RemoveField(
            model_name='note',
            name='analyzing_tokens',
        ),
        migrations.RemoveField(
            model_name='note',
            name='file_duration_seconds',
        ),
        migrations.CreateModel(
            name='TranscriptionUsage',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=12, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.IntegerField(help_text='Audio file duration in seconds')),
                ('cost', models.DecimalField(decimal_places=7, default=0, max_digits=11)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcription_usages', to=settings.AUTH_USER_MODEL)),
                ('note', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcription_usages', to='api.note')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transcription_usages', to='api.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcription_usages', to='api.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=12, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('object_id', models.CharField(max_length=12)),
                ('action', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.IntegerField(help_text='Total number of tokens, input plus output.')),
                ('cost', models.DecimalField(decimal_places=7, default=0, max_digits=11)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_usages', to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_usages', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_usages', to='api.project')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_usages', to='api.workspace')),
            ],
        ),
    ]
