# Generated by Django 4.2.3 on 2024-03-04 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_note_analyzing_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=12, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.TextField(default='')),
                ('filter', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=12, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Text', 'Text'), ('Takeaways', 'Takeaways')], max_length=9)),
                ('question', models.CharField(blank=True, max_length=255)),
                ('content', models.JSONField(null=True)),
                ('filter', models.TextField(default='')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='api.asset')),
                ('takeaways', models.ManyToManyField(related_name='blocks', to='api.takeaway')),
            ],
            options={
                'ordering': ('asset', 'order'),
            },
        ),
    ]
