# Generated by Django 4.2.3 on 2024-04-05 04:33

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_add_pgvector"),
    ]

    operations = [
        migrations.AddField(
            model_name="takeaway",
            name="vector",
            field=pgvector.django.VectorField(dimensions=1536, null=True),
        ),
        migrations.AddIndex(
            model_name="takeaway",
            index=pgvector.django.HnswIndex(
                fields=["vector"],
                name="takeaway-vector-index",
                opclasses=["vector_ip_ops"],
            ),
        ),
    ]
