# Generated by Django 4.2.3 on 2024-04-05 04:40

import pgvector.django
from django.db import migrations
from langchain_openai import OpenAIEmbeddings

embeddings = OpenAIEmbeddings(model="text-embedding-3-small")


def initialize_takeaway_vector(apps, schema_editor):
    Takeaway = apps.get_model("api", "Takeaway")
    takeaways = Takeaway.objects.all()
    titles = [takeaway.title for takeaway in takeaways]
    vectors = embeddings.embed_documents(titles)
    takeaways_to_update = []
    for i, takeaway in enumerate(takeaways):
        takeaway.vector = vectors[i]
        takeaways_to_update.append(takeaway)
    Takeaway.objects.bulk_update(takeaways_to_update, ["vector"])


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0025_takeaway_vector"),
    ]

    operations = [
        migrations.RunPython(
            code=initialize_takeaway_vector,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="takeaway",
            name="vector",
            field=pgvector.django.VectorField(dimensions=1536),
        ),
    ]
