# Generated by Django 4.2.3 on 2024-04-17 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_takeaway_vector'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='api.block')),
                ('takeaways', models.ManyToManyField(related_name='themes', to='api.takeaway')),
            ],
            options={
                'ordering': ('block', 'order'),
                'unique_together': {('block', 'title')},
            },
        ),
    ]
