# Generated by Django 4.2.3 on 2024-04-05 04:40

import json

import environ
from django.db import migrations, models
from playwright.sync_api import sync_playwright

import api.models.note

blank_state = {
    "root": {
        "children": [
            {
                "children": [],
                "direction": None,
                "format": "",
                "indent": 0,
                "type": "paragraph",
                "version": 1,
            }
        ],
        "direction": None,
        "format": "",
        "indent": 0,
        "type": "root",
        "version": 1,
    }
}


def migrate_notes_content_to_lexical(apps, schema_editor):
    Note = apps.get_model("api", "Note")
    env = environ.Env()
    environ.Env.read_env(".env")
    environ.Env.read_env(".env.example")
    frontend_url = env("FRONTEND_URL")
    notes = list(Note.objects.all())
    if len(notes) == 0:
        return
    new_note_contents = []
    with sync_playwright() as playwright:
        browser = playwright.chromium.launch(timeout=300000)
        page = browser.new_page()
        page.goto(frontend_url + "/lexical/convert")
        for note in notes:
            if note.content is None:
                note.content = blank_state
                new_note_contents.append(note)
                continue
            page.locator("#clear-text").click()
            page.locator("#draft-js-json-input").fill(json.dumps(note.content))
            output_str = page.locator("#lexical-json-output").text_content()
            note.content = json.loads(output_str)
            new_note_contents.append(note)
    Note.objects.bulk_update(new_note_contents, ["content"])


def remove_highlights(apps, schema_editor):
    Highlight = apps.get_model("api", "Highlight")
    for highlight in Highlight.objects.all():
        highlight.delete(keep_parents=True)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_alter_block_type"),
    ]

    operations = [
        migrations.RunPython(
            code=migrate_notes_content_to_lexical,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=remove_highlights,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddField(
            model_name="highlight",
            name="quote",
            field=models.CharField(default=None, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="note",
            name="content",
            field=models.JSONField(default=api.models.note.blank_content),
        ),
    ]
