# Generated by Django 4.2.3 on 2024-05-28 11:42

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_note_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteProperty',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=12, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('text_value', models.TextField(blank=True)),
                ('number_value', models.DecimalField(decimal_places=10, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='note_properties', to='api.note')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=12, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('data_type', models.CharField(choices=[('Text', 'Text'), ('Number', 'Number'), ('Select', 'Select'), ('MultiSelect', 'Multiselect')], default='Text', max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='api.project')),
            ],
            options={
                'ordering': ('project', 'order'),
                'unique_together': {('name', 'project')},
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=12, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.property')),
            ],
            options={
                'ordering': ('property', 'order'),
                'unique_together': {('name', 'property')},
            },
        ),
        migrations.CreateModel(
            name='NotePropertyOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.noteproperty')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.option')),
            ],
            options={
                'ordering': ('note_property', 'order'),
                'unique_together': {('note_property', 'option')},
            },
        ),
        migrations.AddField(
            model_name='noteproperty',
            name='options',
            field=models.ManyToManyField(related_name='note_properties', through='api.NotePropertyOption', to='api.option'),
        ),
        migrations.AddField(
            model_name='noteproperty',
            name='property',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='note_properties', to='api.property'),
        ),
        migrations.AlterUniqueTogether(
            name='noteproperty',
            unique_together={('note', 'property')},
        ),
    ]
