# Generated by Django 4.2.3 on 2024-06-07 14:03

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_notetype_takeawaytype_vector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notetype',
            name='project',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='note_types', to='api.project'),
        ),
        migrations.AlterField(
            model_name='takeawaytype',
            name='project',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='takeaway_types', to='api.project'),
        ),
        migrations.AlterField(
            model_name='takeawaytype',
            name='vector',
            field=pgvector.django.VectorField(default=None, dimensions=1536),
            preserve_default=False,
        ),
    ]
