# Generated by Django 4.2.3 on 2024-06-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_asset_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="block",
            options={},
        ),
        migrations.RemoveField(
            model_name="block",
            name="content",
        ),
        migrations.RemoveField(
            model_name="block",
            name="order",
        ),
        migrations.RemoveField(
            model_name="block",
            name="question",
        ),
        migrations.AlterField(
            model_name="block",
            name="type",
            field=models.CharField(
                choices=[("Takeaways", "Takeaways"), ("Themes", "Themes")], max_length=9
            ),
        ),
    ]
