# Generated by Django 4.2.3 on 2024-06-19 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_block_options_remove_block_content_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='note',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='takeaway',
            name='code',
        ),
        migrations.RemoveField(
            model_name='note',
            name='code',
        ),
        migrations.RemoveField(
            model_name='note',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='note',
            name='takeaway_sequence',
        ),
    ]
