# Generated by Django 4.2.3 on 2024-06-06 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0041_note_slack_channel_id_note_slack_team_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="objective",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="user",
            name="job",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="workspace",
            name="company_size",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1-10", "Size 1 10"),
                    ("11-50", "Size 11 50"),
                    ("51-200", "Size 51 200"),
                    ("201-500", "Size 201 500"),
                    ("501+", "Size 501 Plus"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="industry",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="workspace",
            name="usage_type",
            field=models.CharField(
                choices=[("Personal", "Personal"), ("Work", "Work")],
                default="Work",
                editable=False,
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
