# Generated by Django 4.2.3 on 2024-06-28 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_project_objective_user_job_workspace_company_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='description',
        ),
    ]
