# Generated by Django 4.2.3 on 2024-06-25 10:02

from django.db import migrations

from api.mixpanel import mixpanel


def add_mixpanel_users(apps, schema_editor):
    User = apps.get_model("api", "User")
    if not User.objects.exists():
        return
    for user in User.objects.all():
        mixpanel.people_set(
            user.id,
            {
                "$email": user.email,
                "$first_name": user.first_name,
                "$last_name": user.last_name,
                "$created": user.date_joined,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_remove_theme_description"),
    ]

    operations = [
        migrations.RunPython(
            code=add_mixpanel_users,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
