# Generated by Django 4.2.3 on 2024-07-03 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_message_chunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=12, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(choices=[('number-of-editors', 'Number Of Editors'), ('number-of-projects', 'Number Of Projects'), ('storage-gb-workspace', 'Storage Gb Workspace'), ('storage-mb-single-file', 'Storage Mb Single File'), ('duration-minute-workspace', 'Duration Minute Workspace'), ('number-of-knowledge-sources', 'Number Of Knowledge Sources'), ('duration-minute-single-file', 'Duration Minute Single File')], max_length=100, unique=True)),
                ('unit', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('default', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Product Feature',
                'verbose_name_plural': 'Product Features',
            },
        ),
        migrations.CreateModel(
            name='StripeProduct',
            fields=[
                ('id', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False, verbose_name='Stripe Product ID')),
                ('usage_type', models.CharField(choices=[('Personal', 'Personal'), ('Work', 'Work')], max_length=20, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='workspace',
            name='stripe_customer_id',
            field=models.CharField(blank=True, editable=False, max_length=30),
        ),
        migrations.CreateModel(
            name='StripeSubscription',
            fields=[
                ('id', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False, verbose_name='Stripe Subscription ID')),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('paused', 'Paused')], max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('is_free_trial', models.BooleanField(default=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='api.stripeproduct')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscription', to='api.workspace')),
            ],
            options={
                'verbose_name': 'Stripe Subscription',
                'verbose_name_plural': 'Stripe Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='StripePrice',
            fields=[
                ('id', models.CharField(editable=False, max_length=30, primary_key=True, serialize=False, verbose_name='Stripe Price ID')),
                ('is_active', models.BooleanField()),
                ('nickname', models.CharField(max_length=256, null=True)),
                ('recurring_interval', models.CharField(max_length=30)),
                ('product', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='api.stripeproduct')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=12, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('value', models.PositiveIntegerField()),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_features', to='api.feature')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_features', to='api.stripeproduct')),
            ],
            options={
                'verbose_name': 'Product Feature Assignment',
                'verbose_name_plural': 'Product Feature Assignments',
                'unique_together': {('product', 'feature')},
            },
        ),
        migrations.AddField(
            model_name='feature',
            name='products',
            field=models.ManyToManyField(through='api.ProductFeature', to='api.stripeproduct'),
        ),
    ]
