# Generated by Django 4.2.3 on 2024-07-10 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_alter_stripesubscription_end_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stripesubscription',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('paused', 'Paused')], default='trialing', max_length=20),
        ),
    ]
