# Generated by Django 4.2.3 on 2024-07-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_alter_stripesubscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tutorial',
            field=models.JSONField(default=dict),
        ),
    ]
