# Generated by Django 4.2.3 on 2024-07-17 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_user_tutorial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chunk',
        ),
    ]
