# Generated by Django 4.2.3 on 2024-08-06 03:08

import api.utils.assembly
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_note_google_drive_file_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='clip',
            field=models.FileField(null=True, upload_to='clips/'),
        ),
        migrations.AddField(
            model_name='highlight',
            name='clip_size',
            field=models.PositiveIntegerField(help_text='File size measured in bytes.', null=True),
        ),
        migrations.AddField(
            model_name='highlight',
            name='end',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='highlight',
            name='start',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='highlight',
            name='thumbnail',
            field=models.FileField(null=True, upload_to='thumbnails/'),
        ),
        migrations.AddField(
            model_name='highlight',
            name='thumbnail_size',
            field=models.PositiveIntegerField(help_text='File size measured in bytes.', null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='transcript',
            field=models.JSONField(default=api.utils.assembly.blank_transcript),
        ),
    ]
