# Generated by Django 4.2.3 on 2024-08-08 17:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_highlight_clip_highlight_clip_size_highlight_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayBook',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=12, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clip', models.FileField(max_length=255, null=True, upload_to='attachments/')),
                ('thumbnail', models.ImageField(null=True, upload_to='thumbnails/')),
                ('clip_size', models.PositiveIntegerField(help_text='File size measured in bytes.', null=True)),
                ('thumbnail_size', models.PositiveIntegerField(help_text='Image size measured in bytes.', null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playbooks', to=settings.AUTH_USER_MODEL)),
                ('notes', models.ManyToManyField(related_name='playbooks', to='api.note')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playbooks', to='api.project')),
                ('takeaways', models.ManyToManyField(related_name='playbooks', to='api.takeaway')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playbooks', to='api.workspace')),
            ],
            options={
                'unique_together': {('title', 'project')},
            },
        ),
    ]
