# Generated by Django 4.2.3 on 2024-08-08 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_highlight_clip_highlight_clip_size_highlight_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnails/'),
        ),
    ]
