# Generated by Django 4.2.3 on 2024-08-10 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0011_taskresult_periodic_task_name'),
        ('api', '0053_alter_highlight_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='is_analyzing',
        ),
        migrations.AddField(
            model_name='note',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='django_celery_results.taskresult'),
        ),
    ]
