# Generated by Django 4.2.3 on 2024-08-26 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgvector.django
import shortuuid.django_fields
import numpy as np
from pgvector.django import MaxInnerProduct
from api.models.task_type import default_task_types


def add_default_task_types_for_each_project(apps, schema_editor):
    Project = apps.get_model("api", "Project")
    TaskType = apps.get_model("api", "TaskType")

    task_types_to_create = []
    for project in Project.objects.all():
        existing_task_types = {
            task_type.name: task_type for task_type in project.task_types.all()
        }
        existing_task_type_names = set(existing_task_types.keys())
        for task_type in default_task_types:
            if task_type["name"] not in existing_task_type_names:
                task_types_to_create.append(
                    TaskType(
                        project=project,
                        name=task_type["name"],
                        definition=task_type["definition"],
                        vector=np.random.rand(1536),
                    )
                )

    TaskType.objects.bulk_create(task_types_to_create)


def map_existing_tasks_to_default_task_types(apps, schema_editor):
    Task = apps.get_model("api", "Task")
    TaskType = apps.get_model("api", "TaskType")
    Project = apps.get_model("api", "Project")

    tasks_to_update = []
    default_task_type_names = [task_type["name"] for task_type in default_task_types]
    for project in Project.objects.all():
        target_task_types = project.task_types.filter(name__in=default_task_type_names)
        for task_type in project.task_types.exclude(name__in=default_task_type_names):
            target_task_type = target_task_types.order_by(
                MaxInnerProduct("vector", task_type.vector)
            ).first()
            for task in task_type.tasks.all():
                task.task_type = target_task_type
                tasks_to_update.append(task)
    Task.objects.bulk_update(tasks_to_update, ["type"])
    TaskType.objects.exclude(
        name__in=[task_type["name"] for task_type in default_task_types]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0055_playbook_playbooktakeaway_playbook_takeaways"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskType",
            fields=[
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        editable=False,
                        length=12,
                        max_length=12,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("definition", models.CharField(max_length=255)),
                ("vector", pgvector.django.VectorField(dimensions=1536)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_types",
                        to="api.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        editable=False,
                        length=12,
                        max_length=12,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("vector", pgvector.django.VectorField(dimensions=1536)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("due_date", models.DateField(null=True)),
                (
                    "priority",
                    models.CharField(
                        choices=[("Low", "Low"), ("Med", "Med"), ("High", "High")],
                        max_length=4,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Todo", "Todo"),
                            ("Done", "Done"),
                            ("Overdue", "Overdue"),
                        ],
                        default="Todo",
                        max_length=8,
                    ),
                ),
                ("last_interaction", models.DateTimeField(blank=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="api.note",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="api.tasktype",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="tasktype",
            index=pgvector.django.HnswIndex(
                fields=["vector"],
                name="task-type-vector-index",
                opclasses=["vector_ip_ops"],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tasktype",
            unique_together={("project", "name")},
        ),
        migrations.AddIndex(
            model_name="task",
            index=pgvector.django.HnswIndex(
                fields=["vector"], name="task-vector-index", opclasses=["vector_ip_ops"]
            ),
        ),
        migrations.RunPython(
            code=add_default_task_types_for_each_project,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RunPython(
            code=map_existing_tasks_to_default_task_types,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
