# Generated by Django 4.2.3 on 2024-08-29 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0055_playbook_playbooktakeaway_playbook_takeaways'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=12, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_contacts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='api.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='api.project')),
            ],
            options={
                'unique_together': {('project', 'email')},
            },
        ),
        migrations.CreateModel(
            name='GoogleCalendarAttendee',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=12, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleCalendarChannel',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=12, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('channel_id', models.UUIDField()),
                ('resource_id', models.TextField()),
                ('resource_uri', models.TextField()),
                ('token', models.UUIDField()),
                ('expiration', models.DateTimeField()),
                ('sync_token', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleCalendarEvent',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=12, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('ical_uid', models.TextField(help_text='Google Calendar iCal UID, same for all recurring events')),
                ('event_id', models.TextField(help_text='Google Calendar Event ID, different for each recurring event')),
                ('etag', models.TextField(null=True)),
                ('summary', models.TextField(null=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('status', models.TextField()),
                ('recurring_event_id', models.TextField(null=True)),
                ('html_link', models.URLField(max_length=2000, null=True)),
                ('meeting_url', models.URLField(null=True)),
                ('meeting_platform', models.TextField(choices=[('google_meet', 'Google Meet'), ('zoom', 'Zoom')], null=True)),
                ('raw', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleCalendarEventAttendee',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=12, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('response_status', models.TextField(choices=[('needsAction', 'Needs Action'), ('declined', 'Declined'), ('tentative', 'Tentative'), ('accepted', 'Accepted')])),
                ('organizer', models.BooleanField(default=False)),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendees', to='api.googlecalendarattendee')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_attendees', to='api.googlecalendarevent')),
            ],
            options={
                'unique_together': {('event', 'attendee')},
            },
        ),
        migrations.CreateModel(
            name='GoogleCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('token_uri', models.URLField()),
                ('client_id', models.TextField()),
                ('client_secret', models.TextField()),
                ('scopes', models.JSONField()),
                ('expiry', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_credential', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecallBot',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('meeting_url', models.URLField(max_length=2000)),
                ('join_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting_platform', models.TextField(choices=[('google_meet', 'Google Meet'), ('zoom', 'Zoom')])),
                ('meeting_participants', models.JSONField(null=True)),
                ('status_code', models.TextField(choices=[('ready', 'Ready'), ('joining_call', 'Joining Call'), ('in_waiting_room', 'In Waiting Room'), ('participant_in_waiting_room', 'Participant In Waiting Room'), ('in_call_not_recording', 'In Call Not Recording'), ('recording_permission_allowed', 'Recording Permission Allowed'), ('recording_permission_denied', 'Recording Permission Denied'), ('in_call_recording', 'In Call Recording'), ('call_ended', 'Call Ended'), ('recording_done', 'Recording Done'), ('done', 'Done'), ('fatal', 'Fatal'), ('analysis_done', 'Analysis Done'), ('analysis_failed', 'Analysis Failed'), ('media_expired', 'Media Expired')], null=True)),
                ('status_sub_code', models.TextField(null=True)),
                ('status_message', models.TextField(null=True)),
                ('status_created_at', models.DateTimeField(null=True)),
                ('transcript', models.JSONField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recall_bots', to=settings.AUTH_USER_MODEL)),
                ('event', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recall_bot', to='api.googlecalendarevent')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recall_bots', to='api.project')),
            ],
        ),
        migrations.RemoveField(
            model_name='googledriveoauthstate',
            name='user',
        ),
        migrations.DeleteModel(
            name='GoogleDriveCredential',
        ),
        migrations.DeleteModel(
            name='GoogleDriveOAuthState',
        ),
        migrations.AddField(
            model_name='googlecalendarevent',
            name='attendees',
            field=models.ManyToManyField(related_name='events', through='api.GoogleCalendarEventAttendee', to='api.googlecalendarattendee'),
        ),
        migrations.AddField(
            model_name='googlecalendarevent',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.googlecalendarchannel'),
        ),
        migrations.AddField(
            model_name='googlecalendarchannel',
            name='credential',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_channels', to='api.googlecredential'),
        ),
        migrations.AddField(
            model_name='googlecalendarattendee',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendees', to='api.googlecalendarchannel'),
        ),
        migrations.AddField(
            model_name='googlecalendarattendee',
            name='contacts',
            field=models.ManyToManyField(related_name='attendees', to='api.contact'),
        ),
        migrations.AddField(
            model_name='note',
            name='contacts',
            field=models.ManyToManyField(related_name='notes', to='api.contact'),
        ),
        migrations.AddField(
            model_name='note',
            name='recall_bot',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='note', to='api.recallbot'),
        ),
        migrations.AlterUniqueTogether(
            name='googlecalendarevent',
            unique_together={('channel', 'event_id')},
        ),
        migrations.AlterUniqueTogether(
            name='googlecalendarchannel',
            unique_together={('credential', 'id')},
        ),
        migrations.AlterUniqueTogether(
            name='googlecalendarattendee',
            unique_together={('channel', 'email')},
        ),
    ]
