# Generated by Django 4.2.3 on 2024-09-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_alter_googlecalendarattendee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_shared',
            field=models.BooleanField(default=True),
        ),
    ]
