# Generated by Django 4.2.3 on 2024-09-04 11:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0057_alter_googlecalendarattendee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecalendarevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='googlecalendarevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
