# Generated by Django 4.2.3 on 2024-09-08 21:18

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields
from api.models.note_template import default_templates

def add_default_note_templates_and_types(apps, schema_editor):
    Note = apps.get_model("api", "Note")
    NoteTemplate = apps.get_model("api", "NoteTemplate")
    NoteTemplateType = apps.get_model("api", "NoteTemplateType")

    for note in Note.objects.all():
        for template_data in default_templates:
            note_template = NoteTemplate.objects.create(note=note, name=template_data["name"])
            note_template_types = [
                NoteTemplateType(template=note_template, name=type_name, data={}) 
                for type_name in template_data["types"]
            ]
            NoteTemplateType.objects.bulk_create(note_template_types)

def revert_add_default_note_templates_and_types(apps, schema_editor):
    NoteTemplate = apps.get_model("api", "NoteTemplate")
    NoteTemplateType = apps.get_model("api", "NoteTemplateType")

    NoteTemplateType.objects.all().delete()
    NoteTemplate.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0058_note_is_approved_tasktype_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteTemplate',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=12, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='api.note')),
            ],
            options={
                'unique_together': {('note', 'name')},
            },
        ),
        migrations.CreateModel(
            name='NoteTemplateType',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, editable=False, length=12, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('data', models.JSONField(default=dict)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='api.notetemplate')),
            ],
            options={
                'unique_together': {('template', 'name')},
            },
        ),
        migrations.RunPython(
            code=add_default_note_templates_and_types,
            reverse_code=revert_add_default_note_templates_and_types,
        ),
    ]
