# Generated by Django 4.2.3 on 2023-07-25 04:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspace", "0001_initial"),
        ("tag", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="workspaces",
            field=models.ManyToManyField(blank=True, to="workspace.workspace"),
        ),
    ]
