# Generated by Django 4.2.3 on 2023-11-18 22:45

import django.db.models.deletion
from django.db import migrations, models


def add_tag_project(apps, schema_editor):
    Tag = apps.get_model("tag", "Tag")
    tags = Tag.objects.all()
    for old_tag in tags:
        for takeaway in old_tag.takeaways.all():
            new_tag, _ = Tag.objects.get_or_create(
                name=old_tag.name,
                project=takeaway.note.project,
                defaults={
                    "created_at": old_tag.created_at,
                    "updated_at": old_tag.updated_at,
                },
            )
            new_tag.takeaways.add(takeaway)
            old_tag.takeaways.remove(takeaway)
        assert old_tag.takeaways.count() == 0
        old_tag.delete()


def revert_add_tag_project(apps, schema_editor):
    Tag = apps.get_model("tag", "Tag")
    tags = Tag.objects.all()
    for old_tag in tags:
        for takeaway in old_tag.takeaways.all():
            new_tag, _ = Tag.objects.get_or_create(
                name=old_tag.name,
                project=None,
                defaults={
                    "created_at": old_tag.created_at,
                    "updated_at": old_tag.updated_at,
                },
            )
            new_tag.takeaways.add(takeaway)
            old_tag.takeaways.remove(takeaway)
        assert old_tag.takeaways.count() == 0
        old_tag.delete()


def count_tag_takeaways(apps, schema_editor):
    Tag = apps.get_model("tag", "Tag")
    for tag in Tag.objects.all():
        tag.takeaway_count = tag.takeaways.count()
        tag.save()


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0007_remove_project_status_project_language"),
        ("takeaway", "0014_alter_takeaway_tags"),
        ("tag", "0006_keyword_remove_tag_workspaces"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="project",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="project.project",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="takeaway_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.RunPython(
            code=add_tag_project,
            reverse_code=revert_add_tag_project,
        ),
        migrations.RunPython(
            code=count_tag_takeaways,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="tag",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags",
                to="project.project",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tag",
            unique_together={("name", "project")},
        ),
    ]
