# Generated by Django 4.2.3 on 2023-07-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("note", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="file_type",
            field=models.CharField(
                choices=[("pdf", "PDF"), ("mp3", "MP3"), ("wav", "WAV")],
                default="pdf",
                max_length=3,
            ),
        ),
    ]
