# Generated by Django 4.2.3 on 2023-08-02 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_attachment_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='summary',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
