# Generated by Django 4.2.3 on 2023-08-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("note", "0003_note_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="transcribed_content",
            field=models.TextField(default=''),
        ),
    ]
