# Generated by Django 4.2.3 on 2023-08-06 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeaway', '0001_initial'),
        ('note', '0005_alter_attachment_transcribed_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='takeaways',
            field=models.ManyToManyField(blank=True, to='takeaway.takeaway'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='transcribed_content',
            field=models.TextField(default=''),
        ),
    ]
