# Generated by Django 4.2.3 on 2023-08-07 14:04

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0006_note_takeaways_alter_attachment_transcribed_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=12, max_length=12, prefix='', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=12, max_length=12, prefix='', primary_key=True, serialize=False),
        ),
    ]
