# Generated by Django 4.2.3 on 2023-08-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_auth_user_user_position'),
        ('note', '0007_alter_attachment_id_alter_note_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='company_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='is_published',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='keywords',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='revenue',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='type',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='user_participants',
            field=models.ManyToManyField(to='user.user'),
        ),
    ]
