# Generated by Django 4.2.3 on 2023-08-20 14:49

from django.db import migrations, models
import django.db.models.deletion

def generate_note_code(note_title):
    words = note_title.split()[:3]
    code = ''.join(word[0].upper() for word in words)
    return code

def populate_existing_rows(apps, schema_editor):
    Note = apps.get_model('note', 'Note')
    
    for obj in Note.objects.all():
        obj.workspace = obj.project.workspace
        code = generate_note_code(obj.title)
        counter = 1
        while Note.objects.filter(workspace=obj.workspace, code=code).exists():
            code = f"{code}{counter}"
            counter += 1
        obj.code = code
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_alter_workspace_id'),
        ('note', '0008_note_company_name_note_description_note_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='code',
            field=models.CharField(null=True, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='workspace.workspace'),
        ),
        migrations.RunPython(populate_existing_rows, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='note',
            name='workspace',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='workspace.workspace'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='code',
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='note',
            name='takeaway_sequence',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='note',
            unique_together={('workspace', 'code')},
        ),
    ]
