# Generated by Django 4.2.3 on 2023-08-20 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0009_note_code_note_workspace_alter_note_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='takeaways',
        ),
    ]
