# Generated by Django 4.2.3 on 2023-08-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0010_remove_note_takeaways'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
