# Generated by Django 4.2.3 on 2023-09-11 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0012_alter_note_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='revenue',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=6, null=True),
        ),
    ]
