# Generated by Django 4.2.3 on 2023-09-15 14:23

from django.db import migrations, models

import note.models


class Migration(migrations.Migration):
    dependencies = [
        ("note", "0013_alter_note_revenue"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="attachments",
        ),
        migrations.AddField(
            model_name="note",
            name="file",
            field=models.FileField(
                null=True,
                upload_to="attachments/",
                validators=[
                    note.models.note.validate_file_size,
                    note.models.note.validate_file_type,
                ],
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="file_type",
            field=models.CharField(
                choices=[("pdf", "Pdf"), ("mp3", "Mp3"), ("wav", "Wav")],
                max_length=3,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="is_analyzing",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="Attachment",
        ),
    ]
