# Generated by Django 4.2.3 on 2023-09-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0014_remove_note_attachments_note_file_note_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='sentiment',
            field=models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=8, null=True),
        ),
    ]
