# Generated by Django 4.2.3 on 2023-10-01 11:29

from django.db import migrations, models

replace = {
    'positive': 'Positive',
    'neutral': 'Neutral',
    'negative': 'Negative',
    'low': 'Low',
    'medium': 'Medium',
    'high': 'High',
}

def replace_values(apps, schema_editor):
    Note = apps.get_model('note', 'Note')
    for note in Note.objects.all():
        if note.revenue is not None:
            note.revenue = replace[note.revenue]
        if note.sentiment is not None:
            note.sentiment = replace[note.sentiment]
        note.save()

def revert_replace_values(apps, schema_editor):
    Note = apps.get_model('note', 'Note')
    revert_replace = dict(map(reversed, replace.items()))
    for note in Note.objects.all():
        if note.revenue is not None:
            note.revenue = revert_replace[note.revenue]
        if note.sentiment is not None:
            note.sentiment = revert_replace[note.sentiment]
        note.save()


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0015_note_sentiment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='revenue',
            field=models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='sentiment',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative')], max_length=8, null=True),
        ),
        migrations.RunPython(
            code=replace_values, 
            reverse_code=revert_replace_values,
        ),
    ]
