# Generated by Django 4.2.3 on 2023-10-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0016_alter_note_revenue_alter_note_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_auto_tagged',
            field=models.BooleanField(default=False),
        ),
    ]
