# Generated by Django 4.2.3 on 2023-10-06 00:10

from django.db import migrations, models

import note.models


class Migration(migrations.Migration):
    dependencies = [
        ("note", "0017_note_is_auto_tagged"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="file",
            field=models.FileField(
                max_length=255,
                null=True,
                upload_to="attachments/",
                validators=[
                    note.models.note.validate_file_size,
                    note.models.note.validate_file_type,
                ],
            ),
        ),
    ]
