# Generated by Django 4.2.3 on 2023-10-06 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0018_alter_note_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='file_type',
            field=models.CharField(choices=[('docx', 'Docx'), ('flac', 'Flac'), ('mp3', 'Mp3'), ('mp4', 'Mp4'), ('pdf', 'Pdf'), ('txt', 'Txt'), ('wav', 'Wav')], max_length=4, null=True),
        ),
    ]
