# Generated by Django 4.2.3 on 2023-10-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0019_alter_note_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='analyzing_cost',
            field=models.DecimalField(decimal_places=7, default=0, max_digits=11),
        ),
        migrations.AddField(
            model_name='note',
            name='analyzing_token',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='note',
            name='file_duration',
            field=models.IntegerField(null=True),
        ),
    ]
