# Generated by Django 4.2.3 on 2023-11-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0006_keyword_remove_tag_workspaces'),
        ('note', '0021_alter_note_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='keywords',
        ),
        migrations.AddField(
            model_name='note',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='tag.keyword'),
        ),
    ]
