# Generated by Django 4.2.3 on 2023-11-10 01:07

from django.db import migrations


def move_note_tags_to_keywords(apps, schema_editor):
    Note = apps.get_model('note', 'Note')
    Keyword = apps.get_model('tag', 'Keyword')

    notes = Note.objects.only('id').all()
    for note in notes:
        tags = note.tags.all()
        for tag in tags:
            keyword, created = Keyword.objects.get_or_create(
                name=tag.name,
                defaults={
                    'created_at': tag.created_at, 
                    'updated_at': tag.updated_at,
                },
            )
            keyword.save()
            note.keywords.add(keyword)
            note.tags.remove(tag)

def reverse_move_note_tags_to_keywords(apps, schema_editor):
    Note = apps.get_model('note', 'Note')
    Tag = apps.get_model('tag', 'Tag')
    Keyword = apps.get_model('tag', 'Keyword')

    notes = Note.objects.all()
    for note in notes:
        keywords = note.keywords.all()
        for keyword in keywords:
            tag, created= Tag.objects.get_or_create(
                name=keyword.name, 
                defaults={
                    'created_at': keyword.created_at, 
                    'updated_at': keyword.updated_at,
                },
            )
            note.tags.add(tag)
            note.keywords.remove(keyword)


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0022_alter_note_keywords'),
    ]

    operations = [
        migrations.RunPython(
            code=move_note_tags_to_keywords,
            reverse_code=reverse_move_note_tags_to_keywords,
        ),
        migrations.RemoveField(
            model_name='note',
            name='tags',
        ),
    ]
