# Generated by Django 4.2.3 on 2023-11-18 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0023_move_note_tags_to_keywords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='analyzing_token',
            new_name='analyzing_tokens',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='file_duration',
            new_name='file_duration_seconds',
        ),
    ]
