# Generated by Django 4.2.3 on 2023-11-25 05:43

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


def move_company_name_to_a_separate_model(apps, schema_editor):
    Note = apps.get_model("note", "Note")
    Organization = apps.get_model("note", "Organization")
    for note in Note.objects.all():
        organization, _ = Organization.objects.get_or_create(
            name=note.company_name,
            project=note.project,
            defaults={
                "created_at": note.created_at,
                "updated_at": note.created_at,
            },
        )
        note.organizations.add(organization)


def revert_move_company_name_to_a_separate_model(apps, schema_editor):
    Note = apps.get_model("note", "Note")
    for note in Note.objects.all():
        organization = note.organizations.first()
        note.company_name = organization.name


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0008_alter_project_language"),
        ("note", "0024_rename_analyzing_token_note_analyzing_tokens_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None,
                        editable=False,
                        length=12,
                        max_length=12,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organizations",
                        to="project.project",
                    ),
                ),
            ],
            options={
                "unique_together": {("project", "name")},
            },
        ),
        migrations.AddField(
            model_name="note",
            name="organizations",
            field=models.ManyToManyField(related_name="notes", to="note.organization"),
        ),
        migrations.RunPython(
            code=move_company_name_to_a_separate_model,
            reverse_code=revert_move_company_name_to_a_separate_model,
        ),
        migrations.RemoveField(
            model_name="note",
            name="company_name",
        ),
    ]
