# Generated by Django 4.2.3 on 2023-12-29 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0025_remove_note_company_name_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='file_type',
            field=models.CharField(choices=[('docx', 'Docx'), ('flac', 'Flac'), ('mp3', 'Mp3'), ('mp4', 'Mp4'), ('pdf', 'Pdf'), ('txt', 'Txt'), ('wav', 'Wav'), ('m4a', 'M4A')], max_length=4, null=True),
        ),
    ]
