# Generated by Django 4.2.3 on 2023-08-18 08:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0003_alter_project_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="members",
            new_name="users",
        ),
    ]
