# Generated by Django 4.2.3 on 2023-11-13 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('en', 'En'), ('id', 'Id')], default='en', max_length=2),
        ),
    ]
