# Generated by Django 4.2.3 on 2023-11-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_remove_project_status_project_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(choices=[('en', 'En'), ('id', 'Id'), ('ja', 'Ja'), ('es', 'Es')], default='en', max_length=2),
        ),
    ]
