# Generated by Django 4.2.3 on 2023-08-18 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_auth_user_user_position'),
        ('takeaway', '0002_alter_takeaway_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='takeaway',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='takeaways', to='user.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='takeaway',
            name='sentiment',
            field=models.CharField(choices=[('positive', 'Positive'), ('neutral', 'Neutral'), ('negative', 'Negative')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='takeaway',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('onhold', 'Onhold'), ('close', 'Close')], default='open', max_length=6),
        ),
        migrations.AddField(
            model_name='takeaway',
            name='upvoted_by',
            field=models.ManyToManyField(to='user.user'),
        ),
    ]
