# Generated by Django 4.2.3 on 2023-08-20 15:39

from django.db import migrations, models
import django.db.models.deletion


def set_note_ids_and_codes(apps, schema_editor):
    Takeaway = apps.get_model('takeaway', 'Takeaway')
    Note = apps.get_model('note', 'Note')
    
    i = 0
    for obj in Takeaway.objects.all():
        obj.note = Note.objects.first()
        obj.code = f'{obj.note.code}-{i + 1}'
        i += 1
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0010_remove_note_takeaways'),
        ('takeaway', '0003_takeaway_created_by_takeaway_sentiment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='takeaway',
            name='code',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='takeaway',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='takeaways', to='note.note'),
            preserve_default=False,
        ),
        migrations.RunPython(set_note_ids_and_codes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='takeaway',
            name='note',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='takeaways', to='note.note'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='takeaway',
            name='code',
            field=models.CharField(default=None, max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
