# Generated by Django 4.2.3 on 2023-09-16 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('takeaway', '0005_alter_takeaway_created_by_alter_takeaway_upvoted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takeaway',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='takeaways', to=settings.AUTH_USER_MODEL),
        ),
    ]
