# Generated by Django 4.2.3 on 2023-10-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takeaway', '0007_remove_takeaway_sentiment_alter_takeaway_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takeaway',
            name='title',
            field=models.TextField(),
        ),
    ]
