# Generated by Django 4.2.3 on 2023-10-17 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('takeaway', '0008_alter_takeaway_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('takeaway_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='takeaway.takeaway')),
                ('start', models.IntegerField()),
                ('end', models.IntegerField()),
            ],
            bases=('takeaway.takeaway',),
        ),
    ]
