# Generated by Django 4.2.3 on 2023-10-25 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_project_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('takeaway', '0009_highlight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=12, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='project.project')),
                ('takeaways', models.ManyToManyField(related_name='insights', related_query_name='insight', to='takeaway.takeaway')),
            ],
        ),
    ]
