# Generated by Django 4.2.3 on 2023-10-31 21:11

import random
import string

import django.db.models.deletion
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import migrations, models


def generate_random_string(length=20):
    # Define the character set from which to generate the string
    characters = string.ascii_letters + string.digits  # You can add more characters if needed

    # Use random.choices to generate the random string
    random_string = ''.join(random.choices(characters, k=length))

    return random_string


def create_raijin_bot():
    User = get_user_model()
    bot = User(
        email='bot@raijin.ai',
        username='bot@raijin.ai',
        first_name='Created by AI',
        last_name='',
    )
    bot.set_password(generate_random_string())
    bot.save()
    return bot


def set_takeaway_created_by_bot(apps, schema_editor):
    bot = create_raijin_bot()
    Takeaway = apps.get_model('takeaway', 'Takeaway')
    Takeaway.objects.filter(created_by=None).update(created_by=bot)


def reverse_set_takeaway_created_by_bot(apps, schema_editor):
    User = get_user_model()
    bot = User.objects.get(username='bot@raijin.ai')
    Takeaway = apps.get_model('takeaway', 'Takeaway')
    Takeaway.objects.filter(created_by=bot.id).update(created_by=None)
    bot.delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('takeaway', '0011_alter_insight_id_alter_takeaway_id'),
    ]

    operations = [
        migrations.RunPython(
            code=set_takeaway_created_by_bot,
            reverse_code=reverse_set_takeaway_created_by_bot,
        ),
        migrations.AlterField(
            model_name='takeaway',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takeaways', to=settings.AUTH_USER_MODEL),
        ),
    ]
