# Generated by Django 4.2.3 on 2023-11-17 07:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('takeaway', '0012_alter_takeaway_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='takeaways',
            field=models.ManyToManyField(related_name='insights', to='takeaway.takeaway'),
        ),
        migrations.AlterField(
            model_name='takeaway',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_takeaways', related_query_name='created_takeaways', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='takeaway',
            name='upvoted_by',
            field=models.ManyToManyField(related_name='upvoted_takeaways', related_query_name='upvoted_takeaways', to=settings.AUTH_USER_MODEL),
        ),
    ]
