# Generated by Django 4.2.3 on 2023-11-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tag", "0006_keyword_remove_tag_workspaces"),
        ("takeaway", "0013_alter_insight_takeaways_alter_takeaway_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="takeaway",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="takeaways", to="tag.tag"
            ),
        ),
    ]
