# Generated by Django 4.2.3 on 2023-12-15 08:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("takeaway", "0014_alter_takeaway_tags"),
        ("note", "0027_alter_note_content"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="highlight",
            name="end",
        ),
        migrations.RemoveField(
            model_name="highlight",
            name="start",
        ),
    ]
