# Generated by Django 4.2.3 on 2023-07-25 04:00

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("logo_url", models.URLField(blank=True)),
                ("domain_slug", models.SlugField(unique=True)),
                (
                    "members",
                    models.ManyToManyField(related_name="workspaces", to="user.user"),
                ),
            ],
        ),
    ]
