# Generated by Django 4.2.3 on 2023-08-07 14:04

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_workspace_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet=None, length=12, max_length=12, prefix='', primary_key=True, serialize=False),
        ),
    ]
