# Generated by Django 4.2.3 on 2023-09-05 03:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("workspace", "0003_alter_workspace_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workspace",
            name="members",
            field=models.ManyToManyField(
                related_name="workspaces", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
